In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("employee_database.db")

In [4]:
conn.execute("""
CREATE TABLE employees (
    emp_id INTEGER,
    emp_name VARCHAR(50),
    department_id INTEGER,
    salary INTEGER,
    location VARCHAR(50)
);
""")

In [5]:
conn.execute("""
CREATE TABLE departments (
    department_id INTEGER,
    department_name VARCHAR(50)
);
""")

In [6]:
conn.executemany("""
INSERT INTO employees
(emp_id, emp_name, department_id, salary, location)
VALUES (?, ?, ?, ?, ?)
""", [
    (1, 'Amit', 101, 75000, 'Pune'),
    (2, 'Sneha', 102, 55000, 'Mumbai'),
    (3, 'Rahul', 101, 90000, 'Pune'),
    (4, 'Priya', 103, 45000, 'Delhi'),
    (5, 'Neha', 102, 65000, 'Mumbai'),
    (6, 'Akash', 101, 50000, 'Pune'),
    (7, 'Riya', 103, 85000, 'Delhi'),
    (8, 'Ankit', 102, 70000, 'Mumbai'),
    (9, 'Pooja', 104, 40000, 'Pune'),
    (10, 'Arjun', 104, 95000, 'Pune')
])

conn.executemany("""
INSERT INTO departments
(department_id, department_name)
VALUES (?, ?)
""", [
    (101, 'IT'),
    (102, 'HR'),
    (103, 'Finance'),
    (104, 'Marketing')
])

conn.commit()

In [7]:
#1. Display all employees
query = """
SELECT *
FROM employees;
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary location
0       1     Amit            101   75000     Pune
1       2    Sneha            102   55000   Mumbai
2       3    Rahul            101   90000     Pune
3       4    Priya            103   45000    Delhi
4       5     Neha            102   65000   Mumbai
5       6    Akash            101   50000     Pune
6       7     Riya            103   85000    Delhi
7       8    Ankit            102   70000   Mumbai
8       9    Pooja            104   40000     Pune
9      10    Arjun            104   95000     Pune

In [8]:
#Question 2 — Display employee name and salary
query = """
SELECT emp_name, salary
FROM employees;
"""

pd.read_sql_query(query, conn)

  emp_name  salary
0     Amit   75000
1    Sneha   55000
2    Rahul   90000
3    Priya   45000
4     Neha   65000
5    Akash   50000
6     Riya   85000
7    Ankit   70000
8    Pooja   40000
9    Arjun   95000

In [9]:
#Question 3 — Find unique locations
query = """
SELECT DISTINCT location
FROM employees;
"""

pd.read_sql_query(query, conn)

  location
0     Pune
1   Mumbai
2    Delhi

In [10]:
#Question 4 — Employees earning more than 50,000
query = """
SELECT *
FROM employees
WHERE salary > 50000;
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary location
0       1     Amit            101   75000     Pune
1       2    Sneha            102   55000   Mumbai
2       3    Rahul            101   90000     Pune
3       5     Neha            102   65000   Mumbai
4       7     Riya            103   85000    Delhi
5       8    Ankit            102   70000   Mumbai
6      10    Arjun            104   95000     Pune

In [11]:
#Question 5 — Employees from Pune earning more than 50,000
query = """
SELECT *
FROM employees
WHERE location = 'Pune'
AND salary > 50000;
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary location
0       1     Amit            101   75000     Pune
1       3    Rahul            101   90000     Pune
2      10    Arjun            104   95000     Pune

In [12]:
#Question 6 — Employees from Pune or Mumbai
query = """
SELECT *
FROM employees
WHERE location = 'Pune'
OR location = 'Mumbai';
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary location
0       1     Amit            101   75000     Pune
1       2    Sneha            102   55000   Mumbai
2       3    Rahul            101   90000     Pune
3       5     Neha            102   65000   Mumbai
4       6    Akash            101   50000     Pune
5       8    Ankit            102   70000   Mumbai
6       9    Pooja            104   40000     Pune
7      10    Arjun            104   95000     Pune

In [13]:
#Question 7 — Sort employees by salary from highest to lowest
query = """
SELECT *
FROM employees
ORDER BY salary DESC;
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary location
0      10    Arjun            104   95000     Pune
1       3    Rahul            101   90000     Pune
2       7     Riya            103   85000    Delhi
3       1     Amit            101   75000     Pune
4       8    Ankit            102   70000   Mumbai
5       5     Neha            102   65000   Mumbai
6       2    Sneha            102   55000   Mumbai
7       6    Akash            101   50000     Pune
8       4    Priya            103   45000    Delhi
9       9    Pooja            104   40000     Pune

In [14]:
#Question 8 — Find the highest salary
query = """
SELECT MAX(salary) AS highest_salary
FROM employees;
"""

pd.read_sql_query(query, conn)

   highest_salary
0           95000

In [15]:
#Question 9 — Find average salary
query = """
SELECT AVG(salary) AS average_salary
FROM employees;
"""

pd.read_sql_query(query, conn)

   average_salary
0         67000.0

In [16]:
#Question 10 — Count total employees
query = """
SELECT COUNT(*) AS total_employees
FROM employees;
"""

pd.read_sql_query(query, conn)

   total_employees
0               10

In [17]:
#Question 11 — Find total salary
query = """
SELECT SUM(salary) AS total_salary
FROM employees;
"""

pd.read_sql_query(query, conn)

   total_salary
0        670000

In [18]:
#Question 12 — Count employees in each department
query = """
SELECT department_id,
       COUNT(*) AS employee_count
FROM employees
GROUP BY department_id;
"""

pd.read_sql_query(query, conn)

   department_id  employee_count
0            101               3
1            102               3
2            103               2
3            104               2

In [19]:
#Question 13 — Average salary by departmen
query = """
SELECT department_id,
       AVG(salary) AS average_salary
FROM employees
GROUP BY department_id;
"""

pd.read_sql_query(query, conn)

   department_id  average_salary
0            101    71666.666667
1            102    63333.333333
2            103    65000.000000
3            104    67500.000000

In [20]:
#Question 14 — Departments having more than 5 employees
query = """
SELECT department_id,
       COUNT(*) AS employee_count
FROM employees
GROUP BY department_id
HAVING COUNT(*) > 5;
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [department_id, employee_count]
Index: []

In [21]:
#Question 15 — Departments with average salary above 60,000
query = """
SELECT department_id,
       AVG(salary) AS average_salary
FROM employees
GROUP BY department_id
HAVING AVG(salary) > 60000;
"""

pd.read_sql_query(query, conn)

   department_id  average_salary
0            101    71666.666667
1            102    63333.333333
2            103    65000.000000
3            104    67500.000000

In [22]:
#Question 16 — Employee name with department name
query = """
SELECT e.emp_name,
       d.department_name
FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id;
"""

pd.read_sql_query(query, conn)

  emp_name department_name
0     Amit              IT
1    Sneha              HR
2    Rahul              IT
3    Priya         Finance
4     Neha              HR
5    Akash              IT
6     Riya         Finance
7    Ankit              HR
8    Pooja       Marketing
9    Arjun       Marketing

In [23]:
#Question 17 — Display all employees including those without a department
query = """
SELECT e.emp_name,
       d.department_name
FROM employees e
LEFT JOIN departments d
ON e.department_id = d.department_id;
"""

pd.read_sql_query(query, conn)

  emp_name department_name
0     Amit              IT
1    Sneha              HR
2    Rahul              IT
3    Priya         Finance
4     Neha              HR
5    Akash              IT
6     Riya         Finance
7    Ankit              HR
8    Pooja       Marketing
9    Arjun       Marketing

In [24]:
#Question 18 — Categorize employees based on salary
query = """
SELECT emp_name,
       salary,
       CASE
           WHEN salary >= 80000 THEN 'High'
           WHEN salary >= 50000 THEN 'Medium'
           ELSE 'Low'
       END AS salary_category
FROM employees;
"""

pd.read_sql_query(query, conn)

  emp_name  salary salary_category
0     Amit   75000          Medium
1    Sneha   55000          Medium
2    Rahul   90000            High
3    Priya   45000             Low
4     Neha   65000          Medium
5    Akash   50000          Medium
6     Riya   85000            High
7    Ankit   70000          Medium
8    Pooja   40000             Low
9    Arjun   95000            High

In [25]:
#Question 19 — Employees from Pune and Mumbai using UNION
query = """
SELECT emp_name
FROM employees
WHERE location = 'Pune'

UNION

SELECT emp_name
FROM employees
WHERE location = 'Mumbai';
"""

pd.read_sql_query(query, conn)

  emp_name
0    Akash
1     Amit
2    Ankit
3    Arjun
4     Neha
5    Pooja
6    Rahul
7    Sneha

In [26]:
#Question 20 — Convert employee names to uppercase
query = """
SELECT UPPER(emp_name) AS employee_name
FROM employees;
"""

pd.read_sql_query(query, conn)

  employee_name
0          AMIT
1         SNEHA
2         RAHUL
3         PRIYA
4          NEHA
5         AKASH
6          RIYA
7         ANKIT
8         POOJA
9         ARJUN

In [27]:
#Question 21 — Employees whose name starts with A
query = """
SELECT *
FROM employees
WHERE emp_name LIKE 'A%';
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary location
0       1     Amit            101   75000     Pune
1       6    Akash            101   50000     Pune
2       8    Ankit            102   70000   Mumbai
3      10    Arjun            104   95000     Pune

In [28]:
#Question 22 — Display employee names and their length
query = """
SELECT emp_name,
       LENGTH(emp_name) AS name_length
FROM employees;
"""

pd.read_sql_query(query, conn)

  emp_name  name_length
0     Amit            4
1    Sneha            5
2    Rahul            5
3    Priya            5
4     Neha            4
5    Akash            5
6     Riya            4
7    Ankit            5
8    Pooja            5
9    Arjun            5

In [29]:
#Question 23 — Employees earning more than average salary
query = """
SELECT emp_name,
       salary
FROM employees
WHERE salary > (
    SELECT AVG(salary)
    FROM employees
);
"""

pd.read_sql_query(query, conn)

  emp_name  salary
0     Amit   75000
1    Rahul   90000
2     Riya   85000
3    Ankit   70000
4    Arjun   95000

In [30]:
#Question 24 — Employee(s) with the highest salary
query = """
SELECT emp_id,
       emp_name,
       salary
FROM employees
WHERE salary = (
    SELECT MAX(salary)
    FROM employees
);
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  salary
0      10    Arjun   95000

In [31]:
#Question 25 — Highest-paid employee in each department
query = """
SELECT e.emp_id,
       e.emp_name,
       e.department_id,
       e.salary
FROM employees e
WHERE e.salary = (
    SELECT MAX(e2.salary)
    FROM employees e2
    WHERE e2.department_id = e.department_id
);
"""

pd.read_sql_query(query, conn)

   emp_id emp_name  department_id  salary
0       3    Rahul            101   90000
1       7     Riya            103   85000
2       8    Ankit            102   70000
3      10    Arjun            104   95000